version: "1"

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8278:${DB_PORT}"
    networks:
      - spring-bank-network
  
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    environment:
      DB_TYPE: postgresql
      DB_HOST: database
      DB_PORT: ${DB_PORT}

      DB_NAME: ${DB_NAME}

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    
    depends_on:
      - database
  
    networks:
       - spring-bank-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    environment:
      API_URL: ${API_URL}
    ports:
      - "4200:4200"

    depends_on:
      - database
      - backend

    networks:
      - spring-bank-network
  

networks:
  spring-bank-network: