package bank_manager.back_end.enums;

public enum ActionType {
    CONNECTION,
    DISCONNECTION,
    EMAIL_MODIFICATION,
    PHONE_MODIFICATION,
    FIRST_NAME_MODIFICATION,
    LAST_NAME_MODIFICATION,
    ADDED_ACCOUNT_USER,
    REMOVED_ACCOUNT_USER,
    STARTED_TRANSACTION,
    CANCELED_TRANSACTION,
    FINISHED_TRANSACTION,
    BIRTHDAY_CHANGE

}
